export type Target = string;
export enum TargetSelector {
  Neighbour = '@p',
  All = '@a',
  Self = '@s',
  AllEntities = '@e',
  Random = '@r',
}

export enum Block {
  Air = 'air',
  Stone = 'stone',
  Grass = 'grass',
  Dirt = 'dirt',
  Cobblestone = 'cobblestone',
  Planks = 'planks',
  Sapling = 'sapling',
  Bedrock = 'bedrock',
  FlowingWater = 'flowing_water',
  Water = 'water',
  FlowingLava = 'flowing_lava',
  Lava = 'lava',
  Sand = 'sand',
  Gravel = 'gravel',
  GoldOre = 'gold_ore',
  IronOre = 'iron_ore',
  CoalOre = 'coal_ore',
  Log = 'log',
  Leaves = 'leaves',
  Sponge = 'sponge',
  Glass = 'glass',
  LapisOre = 'lapis_ore',
  LapisBlock = 'lapis_block',
  Dispenser = 'dispenser',
  Sandstone = 'sandstone',
  Noteblock = 'noteblock',
  Bed = 'bed',
  GoldenRail = 'golden_rail',
  DetectorRail = 'detector_rail',
  StickyPiston = 'sticky_piston',
  Web = 'web',
  Tallgrass = 'tallgrass',
  Deadbush = 'deadbush',
  Piston = 'piston',
  Pistonarmcollision = 'pistonarmcollision',
  Wool = 'wool',
  Element0 = 'element_0',
  YellowFlower = 'yellow_flower',
  RedFlower = 'red_flower',
  BrownMushroom = 'brown_mushroom',
  RedMushroom = 'red_mushroom',
  GoldBlock = 'gold_block',
  IronBlock = 'iron_block',
  DoubleStoneSlab = 'double_stone_slab',
  StoneSlab = 'stone_slab',
  BrickBlock = 'brick_block',
  Tnt = 'tnt',
  Bookshelf = 'bookshelf',
  MossyCobblestone = 'mossy_cobblestone',
  Obsidian = 'obsidian',
  Torch = 'torch',
  Fire = 'fire',
  MobSpawner = 'mob_spawner',
  OakStairs = 'oak_stairs',
  Chest = 'chest',
  RedstoneWire = 'redstone_wire',
  DiamondOre = 'diamond_ore',
  DiamondBlock = 'diamond_block',
  CraftingTable = 'crafting_table',
  Wheat = 'wheat',
  Farmland = 'farmland',
  Furnace = 'furnace',
  LitFurnace = 'lit_furnace',
  StandingSign = 'standing_sign',
  OakDoor = 'oak_door',
  Ladder = 'ladder',
  Rail = 'rail',
  StoneStairs = 'stone_stairs',
  WallSign = 'wall_sign',
  Lever = 'lever',
  StonePressurePlate = 'stone_pressure_plate',
  IronDoor = 'iron_door',
  WoodenPressurePlate = 'wooden_pressure_plate',
  RedstoneOre = 'redstone_ore',
  LitRedstoneOre = 'lit_redstone_ore',
  UnlitRedstoneTorch = 'unlit_redstone_torch',
  RedstoneTorch = 'redstone_torch',
  StoneButton = 'stone_button',
  SnowLayer = 'snow_layer',
  Ice = 'ice',
  Snow = 'snow',
  Cactus = 'cactus',
  Clay = 'clay',
  Reeds = 'reeds',
  Jukebox = 'jukebox',
  Fence = 'fence',
  Pumpkin = 'pumpkin',
  Netherrack = 'netherrack',
  SoulSand = 'soul_sand',
  Glowstone = 'glowstone',
  Portal = 'portal',
  LitPumpkin = 'lit_pumpkin',
  Cake = 'cake',
  UnpoweredRepeater = 'unpowered_repeater',
  PoweredRepeater = 'powered_repeater',
  Invisiblebedrock = 'invisiblebedrock',
  WoodenTrapdoor = 'wooden_trapdoor',
  MonsterEgg = 'monster_egg',
  Stonebrick = 'stonebrick',
  BrownMushroomBlock = 'brown_mushroom_block',
  RedMushroomBlock = 'red_mushroom_block',
  IronBars = 'iron_bars',
  GlassPane = 'glass_pane',
  MelonBlock = 'melon_block',
  PumpkinStem = 'pumpkin_stem',
  MelonStem = 'melon_stem',
  Vine = 'vine',
  FenceGate = 'fence_gate',
  BrickStairs = 'brick_stairs',
  StoneBrickStairs = 'stone_brick_stairs',
  Mycelium = 'mycelium',
  Waterlily = 'waterlily',
  NetherBrickBlock = 'nether_brick_block',
  NetherBrickFence = 'nether_brick_fence',
  NetherBrickStairs = 'nether_brick_stairs',
  NetherWart = 'nether_wart',
  EnchantingTable = 'enchanting_table',
  BrewingStand = 'brewing_stand',
  Cauldron = 'cauldron',
  EndPortal = 'end_portal',
  EndPortalFrame = 'end_portal_frame',
  EndStone = 'end_stone',
  DragonEgg = 'dragon_egg',
  RedstoneLamp = 'redstone_lamp',
  LitRedstoneLamp = 'lit_redstone_lamp',
  Dropper = 'dropper',
  ActivatorRail = 'activator_rail',
  Cocoa = 'cocoa',
  SandstoneStairs = 'sandstone_stairs',
  EmeraldOre = 'emerald_ore',
  EnderChest = 'ender_chest',
  TripwireHook = 'tripwire_hook',
  Tripwire = 'tripwire',
  EmeraldBlock = 'emerald_block',
  SpruceStairs = 'spruce_stairs',
  BirchStairs = 'birch_stairs',
  JungleStairs = 'jungle_stairs',
  ImpulseCommandBlock = 'impulse_command_block',
  Beacon = 'beacon',
  CobblestoneWall = 'cobblestone_wall',
  FlowerPot = 'flower_pot',
  Carrots = 'carrots',
  Potatoes = 'potatoes',
  WoodenButton = 'wooden_button',
  Skull = 'skull',
  Anvil = 'anvil',
  TrappedChest = 'trapped_chest',
  LightWeightedPressurePlate = 'light_weighted_pressure_plate',
  HeavyWeightedPressurePlate = 'heavy_weighted_pressure_plate',
  UnpoweredComparator = 'unpowered_comparator',
  PoweredComparator = 'powered_comparator',
  DaylightDetector = 'daylight_detector',
  RedstoneBlock = 'redstone_block',
  QuartzOre = 'quartz_ore',
  Hopper = 'hopper',
  QuartzBlock = 'quartz_block',
  QuartzStairs = 'quartz_stairs',
  DoubleWoodenSlab = 'double_wooden_slab',
  WoodenSlab = 'wooden_slab',
  StainedHardenedClay = 'stained_hardened_clay',
  StainedGlassPane = 'stained_glass_pane',
  Leaves2 = 'leaves2',
  Log2 = 'log2',
  AcaciaStairs = 'acacia_stairs',
  DarkOakStairs = 'dark_oak_stairs',
  Slime = 'slime',
  GlowStick = 'glow_stick',
  IronTrapdoor = 'iron_trapdoor',
  Prismarine = 'prismarine',
  Sealantern = 'sealantern',
  HayBlock = 'hay_block',
  Carpet = 'carpet',
  HardenedClay = 'hardened_clay',
  CoalBlock = 'coal_block',
  PackedIce = 'packed_ice',
  DoublePlant = 'double_plant',
  StandingBanner = 'standing_banner',
  WallBanner = 'wall_banner',
  DaylightDetectorInverted = 'daylight_detector_inverted',
  RedSandstone = 'red_sandstone',
  RedSandstoneStairs = 'red_sandstone_stairs',
  DoubleStoneSlab2 = 'double_stone_slab2',
  StoneSlab2 = 'stone_slab2',
  SpruceFenceGate = 'spruce_fence_gate',
  BirchFenceGate = 'birch_fence_gate',
  JungleFenceGate = 'jungle_fence_gate',
  DarkOakFenceGate = 'dark_oak_fence_gate',
  AcaciaFenceGate = 'acacia_fence_gate',
  RepeatingCommandBlock = 'repeating_command_block',
  ChainCommandBlock = 'chain_command_block',
  HardGlassPane = 'hard_glass_pane',
  HardStainedGlassPane = 'hard_stained_glass_pane',
  ChemicalHeat = 'chemical_heat',
  SpruceDoor = 'spruce_door',
  BirchDoor = 'birch_door',
  JungleDoor = 'jungle_door',
  AcaciaDoor = 'acacia_door',
  DarkOakDoor = 'dark_oak_door',
  GrassPath = 'grass_path',
  Frame = 'frame',
  ChorusFlower = 'chorus_flower',
  PurpurBlock = 'purpur_block',
  ColoredTorchRg = 'colored_torch_rg',
  PurpurStairs = 'purpur_stairs',
  ColoredTorchBp = 'colored_torch_bp',
  UndyedShulkerBox = 'undyed_shulker_box',
  EndBricks = 'end_bricks',
  FrostedIce = 'frosted_ice',
  EndRod = 'end_rod',
  EndGateway = 'end_gateway',
  Magma = 'magma',
  NetherWartBlock = 'nether_wart_block',
  RedNetherBrick = 'red_nether_brick',
  BoneBlock = 'bone_block',
  StructureVoid = 'structure_void',
  ShulkerBox = 'shulker_box',
  PurpleGlazedTerracotta = 'purple_glazed_terracotta',
  WhiteGlazedTerracotta = 'white_glazed_terracotta',
  OrangeGlazedTerracotta = 'orange_glazed_terracotta',
  MagentaGlazedTerracotta = 'magenta_glazed_terracotta',
  LightBlueGlazedTerracotta = 'light_blue_glazed_terracotta',
  YellowGlazedTerracotta = 'yellow_glazed_terracotta',
  LimeGlazedTerracotta = 'lime_glazed_terracotta',
  PinkGlazedTerracotta = 'pink_glazed_terracotta',
  GrayGlazedTerracotta = 'gray_glazed_terracotta',
  SilverGlazedTerracotta = 'silver_glazed_terracotta',
  CyanGlazedTerracotta = 'cyan_glazed_terracotta',
  BlueGlazedTerracotta = 'blue_glazed_terracotta',
  BrownGlazedTerracotta = 'brown_glazed_terracotta',
  GreenGlazedTerracotta = 'green_glazed_terracotta',
  RedGlazedTerracotta = 'red_glazed_terracotta',
  BlackGlazedTerracotta = 'black_glazed_terracotta',
  Concrete = 'concrete',
  Concretepowder = 'concretepowder',
  ChemistryTable = 'chemistry_table',
  UnderwaterTorch = 'underwater_torch',
  ChorusPlant = 'chorus_plant',
  StainedGlass = 'stained_glass',
  Podzol = 'podzol',
  Beetroots = 'beetroots',
  Stonecutter = 'stonecutter',
  Glowingobsidian = 'glowingobsidian',
  Netherreactor = 'netherreactor',
  InfoUpdate = 'info_update',
  InfoUpdate2 = 'info_update2',
  Movingblock = 'movingblock',
  Observer = 'observer',
  StructureBlock = 'structure_block',
  HardGlass = 'hard_glass',
  HardStainedGlass = 'hard_stained_glass',
  Reserved6 = 'reserved6',
  PrismarineStairs = 'prismarine_stairs',
  DarkPrismarineStairs = 'dark_prismarine_stairs',
  PrismarineBricksStairs = 'prismarine_bricks_stairs',
  StrippedSpruceLog = 'stripped_spruce_log',
  StrippedBirchLog = 'stripped_birch_log',
  StrippedJungleLog = 'stripped_jungle_log',
  StrippedAcaciaLog = 'stripped_acacia_log',
  StrippedDarkOakLog = 'stripped_dark_oak_log',
  StrippedOakLog = 'stripped_oak_log',
  BlueIce = 'blue_ice',
  Element1 = 'element_1',
  Element2 = 'element_2',
  Element3 = 'element_3',
  Element4 = 'element_4',
  Element5 = 'element_5',
  Element6 = 'element_6',
  Element7 = 'element_7',
  Element8 = 'element_8',
  Element9 = 'element_9',
  Element10 = 'element_10',
  Element11 = 'element_11',
  Element12 = 'element_12',
  Element13 = 'element_13',
  Element14 = 'element_14',
  Element15 = 'element_15',
  Element16 = 'element_16',
  Element17 = 'element_17',
  Element18 = 'element_18',
  Element19 = 'element_19',
  Element20 = 'element_20',
  Element21 = 'element_21',
  Element22 = 'element_22',
  Element23 = 'element_23',
  Element24 = 'element_24',
  Element25 = 'element_25',
  Element26 = 'element_26',
  Element27 = 'element_27',
  Element28 = 'element_28',
  Element29 = 'element_29',
  Element30 = 'element_30',
  Element31 = 'element_31',
  Element32 = 'element_32',
  Element33 = 'element_33',
  Element34 = 'element_34',
  Element35 = 'element_35',
  Element36 = 'element_36',
  Element37 = 'element_37',
  Element38 = 'element_38',
  Element39 = 'element_39',
  Element40 = 'element_40',
  Element41 = 'element_41',
  Element42 = 'element_42',
  Element43 = 'element_43',
  Element44 = 'element_44',
  Element45 = 'element_45',
  Element46 = 'element_46',
  Element47 = 'element_47',
  Element48 = 'element_48',
  Element49 = 'element_49',
  Element50 = 'element_50',
  Element51 = 'element_51',
  Element52 = 'element_52',
  Element53 = 'element_53',
  Element54 = 'element_54',
  Element55 = 'element_55',
  Element56 = 'element_56',
  Element57 = 'element_57',
  Element58 = 'element_58',
  Element59 = 'element_59',
  Element60 = 'element_60',
  Element61 = 'element_61',
  Element62 = 'element_62',
  Element63 = 'element_63',
  Element64 = 'element_64',
  Element65 = 'element_65',
  Element66 = 'element_66',
  Element67 = 'element_67',
  Element68 = 'element_68',
  Element69 = 'element_69',
  Element70 = 'element_70',
  Element71 = 'element_71',
  Element72 = 'element_72',
  Element73 = 'element_73',
  Element74 = 'element_74',
  Element75 = 'element_75',
  Element76 = 'element_76',
  Element77 = 'element_77',
  Element78 = 'element_78',
  Element79 = 'element_79',
  Element80 = 'element_80',
  Element81 = 'element_81',
  Element82 = 'element_82',
  Element83 = 'element_83',
  Element84 = 'element_84',
  Element85 = 'element_85',
  Element86 = 'element_86',
  Element87 = 'element_87',
  Element88 = 'element_88',
  Element89 = 'element_89',
  Element90 = 'element_90',
  Element91 = 'element_91',
  Element92 = 'element_92',
  Element93 = 'element_93',
  Element94 = 'element_94',
  Element95 = 'element_95',
  Element96 = 'element_96',
  Element97 = 'element_97',
  Element98 = 'element_98',
  Element99 = 'element_99',
  Element100 = 'element_100',
  Element101 = 'element_101',
  Element102 = 'element_102',
  Element103 = 'element_103',
  Element104 = 'element_104',
  Element105 = 'element_105',
  Element106 = 'element_106',
  Element107 = 'element_107',
  Element108 = 'element_108',
  Element109 = 'element_109',
  Element110 = 'element_110',
  Element111 = 'element_111',
  Element112 = 'element_112',
  Element113 = 'element_113',
  Element114 = 'element_114',
  Element115 = 'element_115',
  Element116 = 'element_116',
  Element117 = 'element_117',
  Element118 = 'element_118',
  Seagrass = 'seagrass',
  Coral = 'coral',
  CoralBlock = 'coral_block',
  CoralFan = 'coral_fan',
  CoralFanDead = 'coral_fan_dead',
  CoralFanHang = 'coral_fan_hang',
  CoralFanHang2 = 'coral_fan_hang2',
  CoralFanHang3 = 'coral_fan_hang3',
  Kelp = 'kelp',
  DriedKelpBlock = 'dried_kelp_block',
  AcaciaButton = 'acacia_button',
  BirchButton = 'birch_button',
  DarkOakButton = 'dark_oak_button',
  JungleButton = 'jungle_button',
  SpruceButton = 'spruce_button',
  AcaciaTrapdoor = 'acacia_trapdoor',
  BirchTrapdoor = 'birch_trapdoor',
  DarkOakTrapdoor = 'dark_oak_trapdoor',
  JungleTrapdoor = 'jungle_trapdoor',
  SpruceTrapdoor = 'spruce_trapdoor',
  AcaciaPressurePlate = 'acacia_pressure_plate',
  BirchPressurePlate = 'birch_pressure_plate',
  DarkOakPressurePlate = 'dark_oak_pressure_plate',
  JunglePressurePlate = 'jungle_pressure_plate',
  SprucePressurePlate = 'spruce_pressure_plate',
  CarvedPumpkin = 'carved_pumpkin',
  SeaPickle = 'sea_pickle',
  Conduit = 'conduit',
  TurtleEgg = 'turtle_egg',
  BubbleColumn = 'bubble_column',
  Barrier = 'barrier',
  StoneSlab3 = 'stone_slab3',
  Bamboo = 'bamboo',
  BambooSapling = 'bamboo_sapling',
  Scaffolding = 'scaffolding',
  StoneSlab4 = 'stone_slab4',
  DoubleStoneSlab3 = 'double_stone_slab3',
  DoubleStoneSlab4 = 'double_stone_slab4',
  GraniteStairs = 'granite_stairs',
  DioriteStairs = 'diorite_stairs',
  AndesiteStairs = 'andesite_stairs',
  PolishedGraniteStairs = 'polished_granite_stairs',
  PolishedDioriteStairs = 'polished_diorite_stairs',
  PolishedAndesiteStairs = 'polished_andesite_stairs',
  MossyStoneBrickStairs = 'mossy_stone_brick_stairs',
  SmoothRedSandstoneStairs = 'smooth_red_sandstone_stairs',
  SmoothSandstoneStairs = 'smooth_sandstone_stairs',
  EndBrickStairs = 'end_brick_stairs',
  MossyCobblestoneStairs = 'mossy_cobblestone_stairs',
  NormalStoneStairs = 'normal_stone_stairs',
  SpruceStandingSign = 'spruce_standing_sign',
  SpruceWallSign = 'spruce_wall_sign',
  SmoothStone = 'smooth_stone',
  RedNetherBrickStairs = 'red_nether_brick_stairs',
  SmoothQuartzStairs = 'smooth_quartz_stairs',
  BirchStandingSign = 'birch_standing_sign',
  BirchWallSign = 'birch_wall_sign',
  JungleStandingSign = 'jungle_standing_sign',
  JungleWallSign = 'jungle_wall_sign',
  AcaciaStandingSign = 'acacia_standing_sign',
  AcaciaWallSign = 'acacia_wall_sign',
  DarkoakStandingSign = 'darkoak_standing_sign',
  DarkoakWallSign = 'darkoak_wall_sign',
  Lectern = 'lectern',
  Grindstone = 'grindstone',
  BlastFurnace = 'blast_furnace',
  StonecutterBlock = 'stonecutter_block',
  Smoker = 'smoker',
  LitSmoker = 'lit_smoker',
  CartographyTable = 'cartography_table',
  FletchingTable = 'fletching_table',
  SmithingTable = 'smithing_table',
  Barrel = 'barrel',
  Loom = 'loom',
  Bell = 'bell',
  SweetBerryBush = 'sweet_berry_bush',
  Lantern = 'lantern',
  Campfire = 'campfire',
  LavaCauldron = 'lava_cauldron',
  Jigsaw = 'jigsaw',
  Wood = 'wood',
  Composter = 'composter',
  LitBlastFurnace = 'lit_blast_furnace',
  LightBlock = 'light_block',
  WitherRose = 'wither_rose',
  Stickypistonarmcollision = 'stickypistonarmcollision',
  BeeNest = 'bee_nest',
  Beehive = 'beehive',
  HoneyBlock = 'honey_block',
  HoneycombBlock = 'honeycomb_block',
  Allow = 'allow',
  Deny = 'deny',
  Border = 'border',
  Chalkboard = 'chalkboard',
  Camera = 'camera',
}

export enum Item {
  IronShovel = 'iron_shovel',
  IronPickaxe = 'iron_pickaxe',
  IronAxe = 'iron_axe',
  FlintAndSteel = 'flint_and_steel',
  Apple = 'apple',
  Bow = 'bow',
  Arrow = 'arrow',
  Coal = 'coal',
  Diamond = 'diamond',
  IronIngot = 'iron_ingot',
  GoldIngot = 'gold_ingot',
  IronSword = 'iron_sword',
  WoodenSword = 'wooden_sword',
  WoodenShovel = 'wooden_shovel',
  WoodenPickaxe = 'wooden_pickaxe',
  WoodenAxe = 'wooden_axe',
  StoneSword = 'stone_sword',
  StoneShovel = 'stone_shovel',
  StonePickaxe = 'stone_pickaxe',
  StoneAxe = 'stone_axe',
  DiamondSword = 'diamond_sword',
  DiamondShovel = 'diamond_shovel',
  DiamondPickaxe = 'diamond_pickaxe',
  DiamondAxe = 'diamond_axe',
  Stick = 'stick',
  Bowl = 'bowl',
  MushroomStew = 'mushroom_stew',
  GoldenSword = 'golden_sword',
  GoldenShovel = 'golden_shovel',
  GoldenPickaxe = 'golden_pickaxe',
  GoldenAxe = 'golden_axe',
  String = 'string',
  Feather = 'feather',
  Gunpowder = 'gunpowder',
  WoodenHoe = 'wooden_hoe',
  StoneHoe = 'stone_hoe',
  IronHoe = 'iron_hoe',
  DiamondHoe = 'diamond_hoe',
  GoldenHoe = 'golden_hoe',
  WheatSeeds = 'wheat_seeds',
  Wheat = 'wheat',
  Bread = 'bread',
  LeatherHelmet = 'leather_helmet',
  LeatherChestplate = 'leather_chestplate',
  LeatherLeggings = 'leather_leggings',
  LeatherBoots = 'leather_boots',
  ChainmailHelmet = 'chainmail_helmet',
  ChainmailChestplate = 'chainmail_chestplate',
  ChainmailLeggings = 'chainmail_leggings',
  ChainmailBoots = 'chainmail_boots',
  IronHelmet = 'iron_helmet',
  IronChestplate = 'iron_chestplate',
  IronLeggings = 'iron_leggings',
  IronBoots = 'iron_boots',
  DiamondHelmet = 'diamond_helmet',
  DiamondChestplate = 'diamond_chestplate',
  DiamondLeggings = 'diamond_leggings',
  DiamondBoots = 'diamond_boots',
  GoldenHelmet = 'golden_helmet',
  GoldenChestplate = 'golden_chestplate',
  GoldenLeggings = 'golden_leggings',
  GoldenBoots = 'golden_boots',
  Flint = 'flint',
  Porkchop = 'porkchop',
  CookedPorkchop = 'cooked_porkchop',
  Painting = 'painting',
  GoldenApple = 'golden_apple',
  Sign = 'sign',
  WoodenDoor = 'wooden_door',
  Bucket = 'bucket',
  Minecart = 'minecart',
  Saddle = 'saddle',
  IronDoor = 'iron_door',
  Redstone = 'redstone',
  Snowball = 'snowball',
  Boat = 'boat',
  Leather = 'leather',
  Kelp = 'kelp',
  Brick = 'brick',
  ClayBall = 'clay_ball',
  Reeds = 'reeds',
  Paper = 'paper',
  Book = 'book',
  SlimeBall = 'slime_ball',
  ChestMinecart = 'chest_minecart',
  Egg = 'egg',
  Compass = 'compass',
  FishingRod = 'fishing_rod',
  Clock = 'clock',
  GlowstoneDust = 'glowstone_dust',
  Fish = 'fish',
  CookedFish = 'cooked_fish',
  Dye = 'dye',
  Bone = 'bone',
  Sugar = 'sugar',
  Cake = 'cake',
  Bed = 'bed',
  Repeater = 'repeater',
  Cookie = 'cookie',
  Map = 'map',
  Shears = 'shears',
  Melon = 'melon',
  PumpkinSeeds = 'pumpkin_seeds',
  MelonSeeds = 'melon_seeds',
  Beef = 'beef',
  CookedBeef = 'cooked_beef',
  Chicken = 'chicken',
  CookedChicken = 'cooked_chicken',
  RottenFlesh = 'rotten_flesh',
  EnderPearl = 'ender_pearl',
  BlazeRod = 'blaze_rod',
  GhastTear = 'ghast_tear',
  GoldNugget = 'gold_nugget',
  NetherWart = 'nether_wart',
  Potion = 'potion',
  GlassBottle = 'glass_bottle',
  SpiderEye = 'spider_eye',
  FermentedSpiderEye = 'fermented_spider_eye',
  BlazePowder = 'blaze_powder',
  MagmaCream = 'magma_cream',
  BrewingStand = 'brewing_stand',
  Cauldron = 'cauldron',
  EnderEye = 'ender_eye',
  SpeckledMelon = 'speckled_melon',
  SpawnEgg = 'spawn_egg',
  ExperienceBottle = 'experience_bottle',
  Fireball = 'fireball',
  WritableBook = 'writable_book',
  WrittenBook = 'written_book',
  Emerald = 'emerald',
  Frame = 'frame',
  FlowerPot = 'flower_pot',
  Carrot = 'carrot',
  Potato = 'potato',
  BakedPotato = 'baked_potato',
  PoisonousPotato = 'poisonous_potato',
  Emptymap = 'emptymap',
  GoldenCarrot = 'golden_carrot',
  Skull = 'skull',
  Carrotonastick = 'carrotonastick',
  Netherstar = 'netherstar',
  PumpkinPie = 'pumpkin_pie',
  Fireworks = 'fireworks',
  Fireworkscharge = 'fireworkscharge',
  EnchantedBook = 'enchanted_book',
  Comparator = 'comparator',
  Netherbrick = 'netherbrick',
  Quartz = 'quartz',
  TntMinecart = 'tnt_minecart',
  HopperMinecart = 'hopper_minecart',
  PrismarineShard = 'prismarine_shard',
  Hopper = 'hopper',
  Rabbit = 'rabbit',
  CookedRabbit = 'cooked_rabbit',
  RabbitStew = 'rabbit_stew',
  RabbitFoot = 'rabbit_foot',
  RabbitHide = 'rabbit_hide',
  Horsearmorleather = 'horsearmorleather',
  Horsearmoriron = 'horsearmoriron',
  Horsearmorgold = 'horsearmorgold',
  Horsearmordiamond = 'horsearmordiamond',
  Lead = 'lead',
  NameTag = 'name_tag',
  PrismarineCrystals = 'prismarine_crystals',
  Muttonraw = 'muttonraw',
  Muttoncooked = 'muttoncooked',
  ArmorStand = 'armor_stand',
  EndCrystal = 'end_crystal',
  SpruceDoor = 'spruce_door',
  BirchDoor = 'birch_door',
  JungleDoor = 'jungle_door',
  AcaciaDoor = 'acacia_door',
  DarkOakDoor = 'dark_oak_door',
  ChorusFruit = 'chorus_fruit',
  ChorusFruitPopped = 'chorus_fruit_popped',
  BannerPattern = 'banner_pattern',
  DragonBreath = 'dragon_breath',
  SplashPotion = 'splash_potion',
  LingeringPotion = 'lingering_potion',
  Sparkler = 'sparkler',
  CommandBlockMinecart = 'command_block_minecart',
  Elytra = 'elytra',
  ShulkerShell = 'shulker_shell',
  Banner = 'banner',
  Medicine = 'medicine',
  Balloon = 'balloon',
  SuperFertilizer = 'super_fertilizer',
  Totem = 'totem',
  Bleach = 'bleach',
  IronNugget = 'iron_nugget',
  IceBomb = 'ice_bomb',
  Trident = 'trident',
  Beetroot = 'beetroot',
  BeetrootSeeds = 'beetroot_seeds',
  BeetrootSoup = 'beetroot_soup',
  Salmon = 'salmon',
  Clownfish = 'clownfish',
  Pufferfish = 'pufferfish',
  CookedSalmon = 'cooked_salmon',
  DriedKelp = 'dried_kelp',
  NautilusShell = 'nautilus_shell',
  Appleenchanted = 'appleenchanted',
  HeartOfTheSea = 'heart_of_the_sea',
  TurtleShellPiece = 'turtle_shell_piece',
  TurtleHelmet = 'turtle_helmet',
  PhantomMembrane = 'phantom_membrane',
  Crossbow = 'crossbow',
  SpruceSign = 'spruce_sign',
  BirchSign = 'birch_sign',
  JungleSign = 'jungle_sign',
  AcaciaSign = 'acacia_sign',
  DarkoakSign = 'darkoak_sign',
  SweetBerries = 'sweet_berries',
  Compound = 'compound',
  Record13 = 'record_13',
  RecordCat = 'record_cat',
  RecordBlocks = 'record_blocks',
  RecordChirp = 'record_chirp',
  RecordFar = 'record_far',
  RecordMall = 'record_mall',
  RecordMellohi = 'record_mellohi',
  RecordStal = 'record_stal',
  RecordStrad = 'record_strad',
  RecordWard = 'record_ward',
  Record11 = 'record_11',
  RecordWait = 'record_wait',
  Shield = 'shield',
  Board = 'board',
  Portfolio = 'portfolio',
  Camera = 'camera',
}

export class Position {
  private m_x: number | string;
  private m_y: number | string;
  private m_z: number | string;

  constructor(x?: number | string, y?: number | string, z?: number | string) {
    this.m_x = x || 0;
    this.m_y = y || 0;
    this.m_z = z || 0;
  }

  set X(x: number | string) {
    this.m_x = x
  }
  get X() {
    return this.m_x
  }

  set Y(y: number | string) {
    this.m_y = y
  }
  get Y() {
    return this.m_y
  }

  set Z(z: number | string) {
    this.m_z = z
  }
  get Z() {
    return this.m_z
  }

  toString(): string {
    return `${this.m_x} ${this.m_y} ${this.m_z}`;
  }

  add(position: Position) {
    let x1 = 0;
    let y1 = 0;
    let z1 = 0;
    let x2 = 0;
    let y2 = 0;
    let z2 = 0;
    if (typeof this.m_x === 'string' && this.m_x.startsWith('~')) {
      x1 = Number.parseFloat(this.m_x.substring(1)) + <number>global.player.Position.X;
    } else if (typeof this.m_x === 'number') {
      x1 = this.m_x;
    }
    if (typeof this.m_y === 'string' && this.m_y.startsWith('~')) {
      y1 = Number.parseFloat(this.m_y.substring(1)) + <number>global.player.Position.Y;
    } else if (typeof this.m_y === 'number') {
      y1 = this.m_y;
    }
    if (typeof this.m_z === 'string' && this.m_z.startsWith('~')) {
      z1 = Number.parseFloat(this.m_z.substring(1)) + <number>global.player.Position.Z;
    } else if (typeof this.m_z === 'number') {
      z1 = this.m_z;
    }
    if (typeof position.X === 'string' && position.X.startsWith('~')) {
      x2 = Number.parseFloat(position.X.substring(1)) + <number>global.player.Position.X;
    } else if (typeof position.X === 'number') {
      x2 = position.X;
    }
    if (typeof position.Y === 'string' && position.Y.startsWith('~')) {
      y2 = Number.parseFloat(position.Y.substring(1)) + <number>global.player.Position.Y;
    } else if (typeof position.Y === 'number') {
      y2 = position.Y;
    }
    if (typeof position.Z === 'string' && position.Z.startsWith('~')) {
      z2 = Number.parseFloat(position.Z.substring(1)) + <number>global.player.Position.Z;
    } else if (typeof position.Z === 'number') {
      z2 = position.Z;
    }

    return new Position(
      x1 + x2,
      y1 + y2,
      z1 + z2
    )
  }
}

export enum MaskMode {
  Filtered = 'filtered',
  Masked = 'masked',
  Replace = 'replace',
  All = 'all',
}

export enum CloneMode {
  Force = 'force',
  Move = 'move',
  Filtered = 'filtered',
  Normal = 'normal',
}

export enum Difficulty {
  Peaceful = 'peaceful',
  Easy = 'easy',
  Normal = 'normal',
  Hard = 'hard',
}

export enum Effect {
  Clear = 'clear',
  Speed = 'speed',
  Slowness = 'slowness',
  Haste = 'haste',
  MiningFatigue = 'mining_fatigue',
  Strength = 'strength',
  InstantHealth = 'instant_health',
  InstantDamage = 'instant_damage',
  JumpBoost = 'jump_boost',
  Nausea = 'nausea',
  Regeneration = 'regeneration',
  Resistance = 'resistance',
  FireResistance = 'fire_resistance',
  WaterBreathing = 'water_breathing',
  Invisibility = 'invisibility',
  Blindness = 'blindness',
  NightVision = 'night_vision',
  Hunger = 'hunger',
  Weakness = 'weakness',
  Poison = 'poison',
  Wither = 'wither',
  HealthBoost = 'health_boost',
  Absorption = 'absorption',
  Saturation = 'saturation',
  Levitation = 'levitation',
  FatalPoison = 'fatal_poison',
  ConduitPower = 'conduit_power',
  SlowFalling = 'slow_falling',
  BadOmen = 'bad_omen',
  VillageHero = 'village_hero',
  Luck = 'lack',
  UnLuck = 'unlack',
}

export enum Enchant {
  Protection = 'protection',
  FireProtection = 'fire_protection',
  FeatherFalling = 'feather_falling',
  BlastProtection = 'blast_protection',
  ProjectileProtection = 'projectile_protection',
  Thorns = 'thorns',
  Respiration = 'respiration',
  DepthStrider = 'depth_strider',
  AquaAffinity = 'aqua_affinity',
  Sharpness = 'sharpness',
  Smite = 'smite',
  BaneOfArthropods = 'bane_of_arthropods',
  Knockback = 'knockback',
  FireAspect = 'fire_aspect',
  Looting = 'looting',
  Efficiency = 'efficiency',
  SilkTouch = 'silk_touch',
  Durability = 'durability',
  Fortune = 'fortune',
  Power = 'power',
  Punch = 'punch',
  Flame = 'flame',
  Infinity = 'infinity',
  LuckOfTheSea = 'luck_of_the_sea',
  Lure = 'lure',
  Mending = 'mending',
  FrostWalker = 'frost_walker',
  BindingCurse = 'binding_curse',
  VanishingCurse = 'vanishing_curse',
  Impaling = 'impaling',
  Riptide = 'riptide',
  Loyalty = 'loyalty',
  Channeling = 'channeling',
  SweepingEdge = 'sweeping_edge',
  Multishot = 'multishot',
  Piercing = 'piercing',
  QuickCharge = 'quick_charge',
  SoulSpeed = 'soul_speed',
}

export enum Commands {
  Clear = 'clear',
  Clone = 'clone',
  Deop = 'deop',
  Detect = 'detect',
  Difficulty = 'difficulty',
  Effect = 'effect',
  Enchant = 'enchant',
  Execute = 'execute',
  Experience = 'experience',
  Fill = 'fill',
  Function = 'function',
  GameMode = 'gamemode',
  GameRule = 'gamerule',
  Give = 'give',
  Help = 'help',
  Kill = 'kill',
  List = 'list',
  Locate = 'locate',
  Me = 'me',
  Mixer = 'mixer',
  MobEvent = 'mobevent',
  Msg = 'msg',
  Op = 'op',
  Particle = 'particle',
  PlaySound = 'playsound',
  Reload = 'reload',
  ReplaceItem = 'replaceitem',
  Say = 'say',
  ScoreBoard = 'scoreboard',
  SetBlock = 'setblock',
  SetMaxPlayers = 'setmaxplayers',
  SetWorldSpawn = 'setworldspawn',
  SpawnPoint = 'spawnpoint',
  SpreadPlayers = 'spreadplayers',
  StopSound = 'stopsound',
  Summon = 'summon',
  Tag = 'tag',
  Teleport = 'teleport',
  Tell = 'tell',
  TellRaw = 'tellraw',
  TestFor = 'testfor',
  TestForBlock = 'testforblock',
  TestForBlocks = 'testforblocks',
  TickingArea = 'tickingarea',
  Time = 'time',
  Title = 'title',
  ToggleDownfall = 'toggledownfall',
  Tp = 'tp',
  TransferServer = 'transferserver',
  W = 'w',
  Weather = 'weather',
  WorldBuilder = 'worldbuilder',
  WSServer = 'wsserver',
  Xp = 'xp',
}

export enum OldBlockHandling {
  Destroy = 'destroy',
  Hollow = 'hollow',
  Keep = 'keep',
  Outline = 'outline',
  Replace = 'replace',
}

export enum GameMode {
  Survival = 'survival',
  Creative = 'creative',
  Adventure = 'adventure',
}

export enum Rule {
  CommandBlocksEnabled = 'commandBlocksEnabled',
  CommandBlockOutput = 'commandBlockOutput',
  DoDaylightCycle = 'doDaylightCycle',
  DoEntityDrops = 'doEntityDrops',
  DoFireTick = 'doFireTick',
  DoMobLoot = 'doMobLoot',
  DoMobSpawning = 'doMobSpawning',
  DoTileDrops = 'doTileDrops',
  DoWeatherCycle = 'doWeatherCycle',
  DrowningDamage = 'drowningDamage',
  FallDamage = 'fallDamage',
  FireDamage = 'fireDamage',
  KeepInventory = 'keepInventory',
  MobGriefing = 'mobGriefing',
  PVP = 'pvp',
  RandomTickSpeed = 'randomTickSpeed',
  SendCommandFeedback = 'sendCommandFeedback',
  ShowDeathMessages = 'showDeathMessages',
  SpawnRadius = 'spawnRadius',
}

export enum ListDetails {
  IDs = 'ids',
  Stats = 'stats',
  Uuids = 'uuids',
}

export enum Feature {
  EndCity = 'EndCity',
  Fortress = 'Fortress',
  Mansion = 'Mansion',
  Mineshaft = 'Mineshaft',
  Monument = 'Monument',
  Stronghold = 'Stronghold',
  Temple = 'Temple',
  Village = 'Village',
}

export enum MixerControl {
  Stop = 'stop',
  Scene = 'scene',
  Start = 'start',
}

export enum MobEvent {
  PillagerPatrolsEvent = 'pillager_patrols_event',
  WanderingTraderEvent = 'wandering_trader_event',
  EventsEnabled = 'events_enabled',
}

export enum Particle {
  AmbientEntityEffect = 'ambient_entity_effect',
  AngryVillager = 'angry_villager',
  Ash = 'ash',
  Barrier = 'barrier',
  Block = 'block',
  Bubble = 'bubble',
  BubbleColumnUp = 'bubble_column_up',
  BubblePop = 'bubble_pop',
  CampfireCosySmoke = 'campfire_cosy_smoke',
  CampfireSignalSmoke = 'campfire_signal_smoke',
  Cloud = 'cloud',
  Composter = 'composter',
  CrimsonSpore = 'crimson_spore',
  Crit = 'crit',
  CurrentDown = 'current_down',
  DamageIndicator = 'damage_indicator',
  Dolphin = 'dolphin',
  DragonBreath = 'dragon_breath',
  DrippingHoney = 'dripping_honey',
  DrippingLava = 'dripping_lava',
  DrippingObsidianTear = 'dripping_obsidian_tear',
  DrippingWater = 'dripping_water',
  Dust = 'dust',
  Effect = 'effect',
  ElderGuardian = 'elder_guardian',
  Enchant = 'enchant',
  EnchantedHit = 'enchanted_hit',
  EndRod = 'end_rod',
  EntityEffect = 'entity_effect',
  Explosion = 'explosion',
  ExplosionEmitter = 'explosion_emitter',
  FallingDust = 'falling_dust',
  FallingHoney = 'falling_honey',
  FallingLava = 'falling_lava',
  FallingNectar = 'falling_nectar',
  FallingObsidianTear = 'falling_obsidian_tear',
  FallingWater = 'falling_water',
  Firework = 'firework',
  Fishing = 'fishing',
  Flame = 'flame',
  Flash = 'flash',
  HappyVillager = 'happy_villager',
  Heart = 'heart',
  InstantEffect = 'instant_effect',
  Item = 'item',
  ItemSlime = 'item_slime',
  ItemSnowball = 'item_snowball',
  LandingHoney = 'landing_honey',
  LandingLava = 'landing_lava',
  LandingObsidianTear = 'landing_obsidian_tear',
  LargeSmoke = 'large_smoke',
  Lava = 'lava',
  Mycelium = 'mycelium',
  Nautilus = 'nautilus',
  Note = 'note',
  Poof = 'poof',
  Portal = 'portal',
  Rain = 'rain',
  Smoke = 'smoke',
  Sneeze = 'sneeze',
  SoulFireFlame = 'soul_fire_flame',
  Spit = 'spit',
  Splash = 'splash',
  SquidInk = 'squid_ink',
  SweepAttack = 'sweep_attack',
  TotemOfUndying = 'totem_of_undying',
  Underwater = 'underwater',
  WarpedSpore = 'warped_spore',
  Witch = 'witch',
}

export enum ParticleMode {
  Force = 'force',
}

export enum ReplaceItemType {
  Block = 'block',
  Entity = 'entity',
}

export enum SlotType {
  ArmorChest = 'slot.armor.chest',
  ArmorFeet = 'slot.armor.feet',
  ArmorHead = 'slot.armor.head',
  ArmorLegs = 'slot.armor.legs',
  WeaponMainHand = 'slot.weapon.mainhand',
  WeaponOffHand = 'slot.weapon.offhand',
  HorseSaddle = 'slot.horse.saddle',
  HorseChest = 'slot.horse.chest',
  HorseArmor = 'slot.horse.armor',
}

export type CustomSlotType = string;

export class SlotTypeGenerator {
  static enderChest = (slotNumber: number): CustomSlotType => `slot.enderchest.${slotNumber}`;
  static hotBar = (slotNumber: number): CustomSlotType => `slot.hotbar.${slotNumber}`;
  static inventory = (slotNumber: number): CustomSlotType => `slot.inventory.${slotNumber}`;
  static horse = (slotNumber: number): CustomSlotType => `slot.horse.${slotNumber}`;
  static villager = (slotNumber: number): CustomSlotType => `slot.villager.${slotNumber}`;
}

export enum EntityType {
  Item = 'item',
  XpOrb = 'xp_orb',
  Tnt = 'tnt',
  FallingBlock = 'falling_block',
  MovingBlock = 'moving_block',
  ArmorStand = 'armor_stand',
  XpBottle = 'xp_bottle',
  EyeOfEnderSignal = 'eye_of_ender_signal',
  EnderCrystal = 'ender_crystal',
  FireworksRocket = 'fireworks_rocket',
  ThrownTrident = 'thrown_trident',
  ShulkerBullet = 'shulker_bullet',
  FishingHook = 'fishing_hook',
  DragonFireball = 'dragon_fireball',
  Arrow = 'arrow',
  Snowball = 'snowball',
  Egg = 'egg',
  Painting = 'painting',
  Minecart = 'minecart',
  LargeFireball = 'large_fireball',
  SplashPotion = 'splash_potion',
  EnderPearl = 'ender_pearl',
  LeashKnot = 'leash_knot',
  WitherSkull = 'wither_skull',
  Boat = 'boat',
  WitherSkullDangerous = 'wither_skull_dangerous',
  LightningBolt = 'lightning_bolt',
  SmallFireball = 'small_fireball',
  AreaEffectCloud = 'area_effect_cloud',
  HopperMinecart = 'hopper_minecart',
  TntMinecart = 'tnt_minecart',
  ChestMinecart = 'chest_minecart',
  CommandBlockMinecart = 'command_block_minecart',
  LingeringPotion = 'lingering_potion',
  LlamaSpit = 'llama_spit',
  EvocationFang = 'evocation_fang',
  IceBomb = 'ice_bomb',
  Balloon = 'balloon',
  Zombie = 'zombie',
  Creeper = 'creeper',
  Skeleton = 'skeleton',
  Spider = 'spider',
  ZombiePigman = 'zombie_pigman',
  Slime = 'slime',
  Enderman = 'enderman',
  Silverfish = 'silverfish',
  CaveSpider = 'cave_spider',
  Ghast = 'ghast',
  MagmaCube = 'magma_cube',
  Blaze = 'blaze',
  ZombieVillager = 'zombie_villager',
  Witch = 'witch',
  Stray = 'stray',
  Husk = 'husk',
  WitherSkeleton = 'wither_skeleton',
  Guardian = 'guardian',
  ElderGuardian = 'elder_guardian',
  Wither = 'wither',
  EnderDragon = 'ender_dragon',
  Shulker = 'shulker',
  Endermite = 'endermite',
  Vindicator = 'vindicator',
  Phantom = 'phantom',
  Ravager = 'ravager',
  EvocationIllager = 'evocation_illager',
  Vex = 'vex',
  Drowned = 'drowned',
  Pillager = 'pillager',
  ZombieVillagerV2 = 'zombie_villager_v2',
  Chicken = 'chicken',
  Cow = 'cow',
  Pig = 'pig',
  Sheep = 'sheep',
  Wolf = 'wolf',
  Villager = 'villager',
  Mooshroom = 'mooshroom',
  Squid = 'squid',
  Rabbit = 'rabbit',
  Bat = 'bat',
  IronGolem = 'iron_golem',
  SnowGolem = 'snow_golem',
  Ocelot = 'ocelot',
  Horse = 'horse',
  Donkey = 'donkey',
  Mule = 'mule',
  SkeletonHorse = 'skeleton_horse',
  ZombieHorse = 'zombie_horse',
  PolarBear = 'polar_bear',
  Llama = 'llama',
  Parrot = 'parrot',
  Dolphin = 'dolphin',
  Turtle = 'turtle',
  Cat = 'cat',
  Pufferfish = 'pufferfish',
  Salmon = 'salmon',
  Tropicalfish = 'tropicalfish',
  Cod = 'cod',
  Panda = 'panda',
  VillagerV2 = 'villager_v2',
  WanderingTrader = 'wandering_trader',
  Player = 'player',
  Shield = 'shield',
  Npc = 'npc',
  Agent = 'agent',
  TripodCamera = 'tripod_camera',
  Chalkboard = 'chalkboard',
}

export enum TagType {
  Add = 'add',
  List = 'list',
  Remove = 'remove',
}

export type Rotation = string | number;

export enum TimeCommand {
  Add = 'add',
  Query = 'query',
  Set = 'set',
}

export enum Time {
  DayTime = 'daytime',
  GameTime = 'gametime',
  Day = 'day',
  Night = 'night',
}

export enum TitleCommand {
  Title = 'title',
  SubTitle = 'subtitle',
  ActionBar = 'actionbar',
}

export enum WeatherType {
  Clear = 'clear',
  Rain = 'rain',
  Thunder = 'thunder',
}

export class Player {
  private m_gameMode: GameMode;
  private m_id: string;
  private m_yRotation: Rotation;
  private m_position: Position;

  constructor(gameMode?: GameMode, id?: string, yRotation?: Rotation, position?: Position) {
    this.m_gameMode = gameMode || GameMode.Survival;
    this.m_id = id || '';
    this.m_yRotation = yRotation || 0;
    this.m_position = position || new Position(0, 0, 0);
  }

  set GameMode(gameMode: GameMode | number) {
    if (typeof gameMode === 'number') {
      switch (gameMode) {
        case 0: {
          this.m_gameMode = GameMode.Survival;
          break;
        }
        case 1: {
          this.m_gameMode = GameMode.Creative;
          break;
        }
        case 2: {
          this.m_gameMode = GameMode.Adventure;
          break;
        }
      }
    } else {
      this.m_gameMode = gameMode;
    }
  }

  get GameMode(): GameMode | number {
    return this.m_gameMode;
  }

  set ID(id: string) {
    this.m_id = id;
  }

  get ID() {
    return this.m_id;
  }

  set YRotation(yRotation: Rotation) {
    this.m_yRotation = yRotation;
  }

  get YRotation() {
    return this.m_yRotation;
  }

  set Position(position: Position) {
    this.m_position = position;
  }

  get Position() {
    return this.m_position;
  }

  setAll(gameMode: GameMode | number, id: string, yRotation: Rotation, position: Position) {
    this.GameMode = gameMode;
    this.ID = id;
    this.YRotation = yRotation;
    this.Position = position;
  }
}

export interface CommandAndArgs {
  Command: string;
  NamedArgs: { [key: string]: string };
  Args: string[];
}